---

- hosts: localhost

  vars:
    homedir: /home/roman/
    user: roman
    group: roman
    favourite_editor: vim.basic
    project_dir: "{{ homedir }}Projects/" #TODO: this is for job
    #TODO: review global git config
    global_git_config:
      user.name: Roman Nakutnyi
      user.email: rnakutnyi@jerasoft.net #TODO: this is for job
      color.ui: auto
      core.pager: "less -FRSX"
      branch.autosetupmerge: true
      apply.whitespace: nowarn
      status.showuntrackedfiles: all
      push.default: tracking
      rebase.stat: true
      rerere.enabled: true
      gitreview.remote: origin
      alias.st: status
      alias.pr: 'pull --rebase'
      alias.co: checkout
      alias.cm: commit
      alias.dt: difftool
      alias.gr: grep
      alias.br: branch
      diff.tool: meld
    git_repolist_personal:
      - "dev/ansible/ubuntu_config": "git@github.com:nakutnyi/ubuntu_config.git"
      - "dev/study/programming_study": "git@github.com:nakutnyi/programming_study.git"
      - "dev/python/pomodoro-timer": "git@github.com:nakutnyi/pomodoro-timer.git"
      - ".emacs.d/": "git@github.com:nakutnyi/emacs_config.git"

    dconf_config:
      # Make workspaces same as in Ubuntu 18.04
      "/org/compiz/profiles/unity/plugins/core/hsize": "1"
      "/org/compiz/profiles/unity/plugins/core/vsize": "4"
      # The space in the beginning of the following value is necessary,
      # it prevents ansible from translating the value into python objects:
      "/org/gnome/desktop/input-sources/sources": " [('xkb', 'us+colemak'), ('xkb', 'us'), ('xkb', 'ua'), ('xkb', 'ru')]"
      # Minor tweaks
      "/com/canonical/indicator/power/show-percentage": "true"
      "/org/gnome/desktop/interface/clock-show-seconds": "true"
      # Below entries do not work, I leave them below for a reference for manual fix:
      #"/org/compiz/profiles/unity/plugins/grid/put-maximize-key": "<Control><Super>Up"
      #"/org/compiz/profiles/unity/plugins/grid/right-maximize": "<Control><Super>Right"
      #"/org/compiz/profiles/unity/plugins/grid/put-restore-key": "<Control><Super>Down"
      #"/org/compiz/profiles/unity/plugins/grid/left-maximize": "<Control><Super>Left"


  tasks:

    - name: Add repositories
      tags: apps
      become: yes
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - 'ppa:kelleyk/emacs'
        - 'ppa:bit-team/stable'
    
    - name: install apt applications
      tags: apps
      become: yes
      apt:
        name:
          # tools
          - dconf-editor
          - gnome-panel
          # emacs and its plugins
          - emacs
          - yaml-mode
          # python plugins
          - python3-tk
          - pylint
          - pylint3
          - python-pip
          # miscellaneous
          - chromium-browser
          - shutter
          - vim
          - goldendict
          - firefox
          - sqlite3
          - anki
          - vlc
          # for development
          - gitk
          # for external drive encryption
          - gnome-disk-utility
          - cryptsetup
          # for backups
          - backintime-qt4
        state: latest

    - name: Install snap applications
      tags: apps
      become: yes
      snap:
        name:
          - telegram-desktop

    - name: Install python plugins for ansible
      become: yes
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        # psutil is necessary for current ansible playbook
        - psutil
        #- formencode
        #- cookiecutter

    - name: Create directories
      become: yes
      file:
        path: "{{ homedir }}/{{ item }}" 
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0755
      with_items:
        - "Soft/goldendict"
        - "dev/python"
        - "dev/study"
        - "backup"
        - "Projects/vcs/" #TODO: this is for job

    - name: Ensure that autostart directory exists
      file:
        path: "/home/roman/.config/autostart/"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0755

    - name: Set Startup applications
      file:
        state: link
        force: yes
        src: "/usr/share/applications/{{ item }}.desktop"
        dest: "{{ homedir }}.config/autostart/{{ item }}.desktop"
      with_items:
        - goldendict
        - firefox
        - chromium-browser

    - name: Dconf configuration
      tags: dconf
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_dict: "{{ dconf_config }}"

    - name: Use CapsLock as CapsLock, not Backspace
      become: yes
      replace:
        path: "/usr/share/X11/xkb/symbols/us"
        regexp: '(^    key <CAPS> { \[    BackSpace,    BackSpace,       BackSpace,        BackSpace \] };)$'
        replace: '//\1' 

    - name: Allow core dumps for the user (for C debugging)
      become: yes
      pam_limits:
        domain: "{{ user }}"
        limit_type: soft
        limit_item: core
        value: 8192

    - name: Tweak for Visual Studio Code
      become: yes
      sysctl:
        name: fs.inotify.max_user_watches
        value: 524288

    - name: Allow for long command line history within a bash session
      replace:
        path: "{{ homedir }}/.bashrc"
        regexp: '^HISTSIZE=.*$'
        replace: 'HISTSIZE=10000'

    - name: Allow for long command line history stored in a history file
      replace:
        path: "{{ homedir }}/.bashrc"
        regexp: '^HISTFILESIZE=.*$'
        replace: 'HISTFILESIZE=20000'

    - name: Block distracting sites.
      become: yes
      blockinfile: |
        dest=/etc/hosts
        content="#Block junk sites
        127.0.0.1 www.youtube.com
        127.0.0.1 www.facebook.com
        127.0.0.1 bash.im"

    - name: Get vim location
      shell: "which {{ favourite_editor }}"
      register: command_output

    - name: Set editor_path variable
      set_fact:
        editor_path: "{{ command_output.stdout_lines[0] }}"

    - name: Setup selected editor in a config file
      lineinfile:
        create: yes
        dest: "{{ homedir }}/.selected_editor"
        regexp: "SELECTED_EDITOR="
        line: 'SELECTED_EDITOR="{{ editor_path }}"'

    - name: Setup selected editor in an environment variable
      lineinfile:
        dest: "{{ homedir }}/.bashrc"
        regexp: "^export EDITOR="
        line: 'export EDITOR="{{ editor_path }}"'

    - name: Initialize personal Git repos
      git:
        update: no
        repo: "{{ item.value }}"
        dest: "{{ homedir }}/{{ item.key }}"
      with_dict: "{{ git_repolist_personal }}"

    - name: Personal git config
      tags: git
      git_config:
        scope: local
        repo: "{{ homedir }}{{ item.key }}"
        name: user.email
        value: nakutnyi@gmail.com
      with_dict: "{{ git_repolist_personal }}"

    - name: Global git config
      tags: git
      become: yes
      git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ global_git_config }}"

    - name: Add aliases and tweaks
      lineinfile:
        dest: "{{ homedir }}/.bashrc"
        line: "{{ item }}"
      #TODO: move aliases to ~/.bash_aliases
      with_items:
        - 'alias g="git"'
        - 'alias conf="cd {{ homedir }}/dev/ansible/ubuntu_config/"'
        - 'alias v="vagrant"'
        # TODO: job stuff
        - 'PATH="$PATH:/usr/local/bin/vendor/bin/"'
        - 'alias work="cd {{ project_dir }}/vcs; source {{ project_dir }}/vcs-python-env/bin/activate"'
        - 'if [[ "$PWD" = {{ project_dir }}vcs* ]]; then { source {{ project_dir }}/vcs-python-env/bin/activate; } fi'
        - 'export LXC_ENABLED="1"' 

    - name: Add autocompletion for aliases
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (autocompletion)"
        path: "{{ homedir }}/.bashrc"
        block: "{{lookup('file', 'templates/bash_aliases_autocompletion')}}"
        state: present
        insertafter: '^.alias.*$'

    - name: Allow colourful prompt in bash
      lineinfile:
        path: "{{ homedir }}/.bashrc"
        regexp: "#?force_color_prompt=yes"
        line: "force_color_prompt=yes"

    - name: Allow colourful prompt for git branch
      lineinfile:
        path: "{{ homedir }}/.bashrc"
        regexp: "#?unset color_prompt force_color_prompt"
        line: "#unset color_prompt force_color_prompt"

    - name: Prepare to add git branch output, remove trailing spaces from prompt
      tags: gitbranch
      replace:
        dest: "{{ homedir }}/.bashrc"
        regexp: "^( *)PS1='(.*) '$"
        replace: "\\1PS1='\\2'"

    - name: Add git branch output to your terminal prompt
      tags: gitbranch
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED BLOCK (git branch in prompt)"
        path: "{{ homedir }}/.bashrc"
        block: "{{lookup('file', 'templates/git_branch_in_prompt')}}"
        state: present
